### ISSUE TITLE
Create Schematic crashes the game in LAN and little quest thing

### ISSUE THREAD

**Issue by Morlullador** [nvb-uy/Prominent#4]
Prominence II [RPG]. Fabric. ver. 2.6.5 (not up to date for personal reasons)

Found a bit of annoying thing in "Getting started" quest chapter. Quest about waystones, there needed specific variant of waystone to interact with. This issue can be simply resolved by changing quest completion requirement from to specific item to #fwaystones:waystones tag.

Also found a bug in Create schematic. All problems was found LAN multiplayer, first of all, it's not working as it's should: rotation, moving and other functions that schematic have simply don't work. Also, using it with Shift+RC opens a menu to both a Server host and a player who actually opened it and if the host tries to close the menu by any methods the game crashes.

**Comment by nvb-uy** [comment]
This is not the place to report bugs of the modpack. This repository is for the core mod of the modpack.
