### ISSUE TITLE
AE2 Crafting with EMI

### ISSUE THREAD

**Issue by BushTrocity** [nvb-uy/Prominent#5]
For 2.7.0 with EMI being added, the AE2 terminal crafting no longer works. AE2 EMI Crafting Integration needs to be added in order to restore crafting from EMI in a AE2 terminal. (client side only not required on server)

**Comment by FunLay123** [comment]
For 2.7.0 With installed AE2 EMI Crafting Integration mod (third-party mod not included in the modpack) ME terminal works almost properly. You can do items on terminal by clicking "plus" in EMI craft menu but can not create missing items that can be crafted by system for recipe by clicking shift + "plus" that can be did in REI before. 
In addition ME Pattern Encoding Terminal can not create patterns without real items unlike it was before. You need to put items manually in recipe craft grid. You can not click "plus" in EMI craft menu and then items will take their place in grid even if you have them.

Sorry for my english.

**Comment by MechanosG** [comment]
If you install JEI client side along side EMI, this will allow you to quick craft with EMI in both the crafting terminal and pattern terminal, and seems to work better than the AE2 EMI Crafting Integration mod. The GUI doesn't tell you to shift+click to fill in missing parts from patterns unfortunately, but it does still highlight those items as blue, and functions properly.

**Comment by nvb-uy** [comment]
This is NOT a place to report issues.
