### ISSUE TITLE
Internal Server randomly stops responding

### ISSUE THREAD

**Issue by ChillFire22** [nvb-uy/Prominent#6]
Hello,
Whilst playing the mod pack (Prominence I FORGE) on singleplayer, the game's internal server randomly stops responding which is visible by commands not working, block breaks not dropping anything, mobs frozen, etc.

The only "fix" I found was crashing the game and re-opening. At which point I get to play for a few to dozen minutes before the same issues occur again.

In one instance, this happened after I pressed 'b' to open my backpack and so I thought it was because of it. Resolved all conflicts on 'b' and tested, everything worked for a while until it happened again. Did not use my backpack at all and still happened.

Another thing I tried is using another shader from the list of the installed ones with the modpack.

Here is the log file
[logs.txt](https://github.com/nvb-uy/Prominent/files/14320228/logs.txt)

**Comment by nvb-uy** [comment]
This is NOT a place to report issues.
