### ISSUE TITLE
Various networking issues affecting our server

### ISSUE THREAD

**Issue by MechanosG** [nvb-uy/Prominent#7]
(Edit:  I probably should have specified, this issue is for Prominence II RPG 2.7.0.)

One of the recent updates (possibly the one that added Very Many Players) seems to have introduced a lot of networking/syncing errors. On our dedicated server running 2.7.0, I often will join the server and have my inventory or nearby blocks get completely scrambled with the wrong items/blocks. Unequipping and re-equipping an item, will resync my inventory and fix that. But the local blocks getting scrambled, don't seem to fix themselves until you force the chunk to reload.

Worse, we've started to see players semi-randomly time out upon joining the server, despite making it into game and walking around briefly. The server doesn't register that they've disconnected however, and shows that they're still in-game. These players become unable to rejoin the server, timing out on all subsequent attempts to rejoin. This just happened to me, and I've been waiting for about an hour now for my character on the server to timeout, but so far it's just stuck, and I'm unable to rejoin.  Other players have visited my character's location and say it just shows me standing there lol.  Previously I didn't have any problems like this, on version 2.6.5 (I think) and older. We've hosted a dedicated server without these issues since 2.2.0, last year.

**Comment by nvb-uy** [comment]
This is NOT a place to report issues.
